export const CAKE_ORDERED = "CAKE_ORDERED";
export const CAKE_SELLED = "CAKE_SELLED";

export const FETCH_USER_REQUEST = "FETCH_USER_REQUEST";
export const FETCH_USER_SUCESS = "FETCH_USER_SUCESS";
export const FETCH_USER_FAILED = "FETCH_USER_FAILED";


export const EMP_FETCH_REQUEST = "EMP_FETCH_REQUEST";
export const EMP_FETCH_SUCESS = "EMP_FETCH_SUCESS";
export const EMP_FETCH_FAIL = "EMP_FETCH_FAIL";